version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
        - dev
        - openai
        - azure_openai
        - bedrock
        - ai21
        - anthropic
        - cohere
        - huggingface-local
        - huggingface-remote
        - vertex
        
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"
  fail_on_warning: true

formats:
  - pdf
