# Config for everything related to dataset generation inputs
input_config:
    # Dataset metadata
    domain: news
    language: en

    # Dataset generator parameters
    quantity: 10
    random_sample_human: true

    # HuggingFace dataset params
    dataset: xsum
    dataset_text_column: document
    dataset_params:
        split: test

    # Prompt template
    template: >-
        Write a news article starting by these two sentences: {sentences},
        whose summary is '{summary}',
        using the entities: {entities}\n\nArticle: 

    # Extractor params
    extractor: combined
    extractors_list:
        - auxiliary.Auxiliary
        - entity_list.EntityList
        - sentence_prefix.SentencePrefix
    max_input_tokens: 256
    
    # We can pass args to the extractors using
    # the `extractor_args` field, which is a dictionary
    # specifying the args for each extractor.
    extractor_args:
        sentence_prefix:
            k: 2
    
# Config for model instantiation
# Requires `OPENAI_API_KEY=<key>` environment variable.
model_config:
    provider: openai
    model_name: gpt-3.5-turbo-instruct
    api_type: COMPLETION
    threads: 8
    max_retries: 5
    timeout: 120
    
# Decoding args
generation_config:
    # Ignore use `max_tokens` to get automatic length estimation
    # max_tokens: 100
    temperature: 0.7
    presence_penalty: 1.0